// Test Scenario Definitions — Great Horn AML Nightwatch
// Internal use only

export const SCENARIO_TYPES = [
  'Canadian Bitcoin Exchange',
  'Bitcoin OTC Desk',
  'Remittance MSB',
  'Cheque Cashing Business',
  'Broken Compliance Program',
];

export const SCENARIO_DEFINITIONS = {
  'Canadian Bitcoin Exchange': {
    defaultClientName: 'Northern Coin Exchange Ltd.',
    clientData: {
      industry: 'Virtual Asset Exchange',
      client_type: 'Virtual Asset Service Provider',
      primary_jurisdiction: 'Canada',
      operating_name: 'NorthernCoin',
    },
    methodologyName: 'Virtual Asset EWRA',
    engagementType: 'Risk Assessment',
    intakeSections: [
      { section: 'business_profile', responses: { legal_entity_name: 'Northern Coin Exchange Ltd.', industry: 'Virtual Asset Exchange', country_of_incorporation: 'Canada', province_state: 'Ontario', regulated: true, licenses_held: 'FINTRAC MSB Registration #M123456789', year_established: 2019 } },
      { section: 'products_services', responses: { products_offered: 'Bitcoin and cryptocurrency spot trading, fiat on/off ramp, institutional OTC', handles_fiat: true, handles_virtual_assets: true, accepts_cash: false, offers_cross_border_services: true, monthly_transaction_volume: 50000000, avg_transaction_size: 5000, max_transaction_size: 500000 } },
      { section: 'delivery_channels', responses: { services_offered_online: true, onboarding_fully_remote: true, transactions_through_api: true, transactions_through_web: true, services_in_person: false } },
      { section: 'customer_base', responses: { client_base: 'both', peps_permitted: true, customers_virtual_asset: true, hnw_clients: true, foreign_customers_permitted: true } },
      { section: 'geography', responses: { countries_customers_located: 'Canada, USA, EU, Singapore', cross_border_permitted: true, high_risk_jurisdictions: true, restricted_to_canada: false } },
      { section: 'aml_controls', responses: { compliance_officer: true, aml_policies: true, procedures_documented: true, sanctions_screening: true, transaction_monitoring: true, staff_training: true, recordkeeping: true, independent_review: false, identity_verification: true, bo_verification: true, client_risk_rated: true, edd_high_risk: true } },
      { section: 'service_providers', responses: { third_party_kyc: true, third_party_sanctions: true, banking_partners: true, liquidity_providers: true, vendor_dd_completed: true } },
      { section: 'technology_security', responses: { mfa: true, rbac: true, internally_developed_software: true, audit_logs: true, backups_recovery: true } },
      { section: 'virtual_asset_module', responses: { supported_assets: 'BTC, ETH, USDT, USDC', onchain_screening: true, travel_rule: true, external_wallets: true, wallet_ownership_attested: true } },
    ],
    scenarioRisks: [
      { risk_name: 'Virtual Asset Trading Services', likelihood: 2, impact: 3, controlEffectiveness: 'Partially Effective' },
      { risk_name: 'Fiat On Off Ramp Services', likelihood: 2, impact: 2, controlEffectiveness: 'Partially Effective' },
      { risk_name: 'High Transaction Velocity', likelihood: 2, impact: 2, controlEffectiveness: 'Partially Effective' },
      { risk_name: 'Non-Face-to-Face Onboarding', likelihood: 2, impact: 2, controlEffectiveness: 'Strong' },
      { risk_name: 'Fully Online Service Delivery', likelihood: 2, impact: 2, controlEffectiveness: 'Strong' },
      { risk_name: 'API Transaction Access', likelihood: 2, impact: 2, controlEffectiveness: 'Partially Effective' },
      { risk_name: 'Corporate Customers', likelihood: 2, impact: 2, controlEffectiveness: 'Partially Effective' },
      { risk_name: 'Virtual Asset Business Clients', likelihood: 2, impact: 3, controlEffectiveness: 'Partially Effective' },
      { risk_name: 'Cross-Border Transaction Activity', likelihood: 2, impact: 3, controlEffectiveness: 'Partially Effective' },
      { risk_name: 'Third-Party KYC Provider Dependence', likelihood: 2, impact: 2, controlEffectiveness: 'Strong' },
      { risk_name: 'Reliance on Automated Systems', likelihood: 2, impact: 2, controlEffectiveness: 'Partially Effective' },
      { risk_name: 'Sanctioned Individual Exposure', likelihood: 2, impact: 3, controlEffectiveness: 'Partially Effective' },
    ],
  },

  'Bitcoin OTC Desk': {
    defaultClientName: 'CanWest OTC Trading Inc.',
    clientData: {
      industry: 'OTC Trading Desk',
      client_type: 'Virtual Asset Service Provider',
      primary_jurisdiction: 'Canada',
    },
    methodologyName: 'Virtual Asset EWRA',
    engagementType: 'Risk Assessment',
    intakeSections: [
      { section: 'business_profile', responses: { legal_entity_name: 'CanWest OTC Trading Inc.', industry: 'OTC Virtual Asset Trading', country_of_incorporation: 'Canada', regulated: true, licenses_held: 'FINTRAC MSB Registration', year_established: 2021 } },
      { section: 'products_services', responses: { products_offered: 'Large block Bitcoin and digital asset OTC trades for institutional and HNW clients', handles_fiat: true, handles_virtual_assets: true, accepts_cash: false, offers_cross_border_services: true, monthly_transaction_volume: 100000000, avg_transaction_size: 500000, max_transaction_size: 10000000 } },
      { section: 'delivery_channels', responses: { services_offered_online: true, onboarding_fully_remote: true, transactions_through_api: false, transactions_through_web: true, services_in_person: false } },
      { section: 'customer_base', responses: { client_base: 'both', peps_permitted: true, hnw_clients: true, foreign_customers_permitted: true, entity_foreign_bos: true } },
      { section: 'geography', responses: { cross_border_permitted: true, high_risk_jurisdictions: true, restricted_to_canada: false } },
      { section: 'aml_controls', responses: { compliance_officer: true, aml_policies: true, sanctions_screening: true, transaction_monitoring: true, staff_training: true, independent_review: false, identity_verification: true, bo_verification: true } },
      { section: 'service_providers', responses: { third_party_kyc: true, banking_partners: true, liquidity_providers: true } },
      { section: 'virtual_asset_module', responses: { supported_assets: 'BTC, ETH', external_wallets: true, travel_rule: true, onchain_screening: true } },
    ],
    scenarioRisks: [
      { risk_name: 'OTC Trading Services', likelihood: 2, impact: 3, controlEffectiveness: 'Partially Effective' },
      { risk_name: 'High-Value Transaction Capability', likelihood: 2, impact: 3, controlEffectiveness: 'Partially Effective' },
      { risk_name: 'Non-Face-to-Face Onboarding', likelihood: 2, impact: 2, controlEffectiveness: 'Strong' },
      { risk_name: 'Corporate Customers', likelihood: 2, impact: 2, controlEffectiveness: 'Partially Effective' },
      { risk_name: 'Politically Exposed Persons', likelihood: 2, impact: 3, controlEffectiveness: 'Strong' },
      { risk_name: 'Cross-Border Transaction Activity', likelihood: 2, impact: 3, controlEffectiveness: 'Partially Effective' },
      { risk_name: 'Foreign Beneficial Owners', likelihood: 2, impact: 2, controlEffectiveness: 'Partially Effective' },
      { risk_name: 'Third-Party KYC Provider Dependence', likelihood: 2, impact: 2, controlEffectiveness: 'Strong' },
      { risk_name: 'Sanctioned Entity Exposure', likelihood: 2, impact: 3, controlEffectiveness: 'Partially Effective' },
    ],
  },

  'Remittance MSB': {
    defaultClientName: 'TransCanada Money Transfer Ltd.',
    clientData: {
      industry: 'Money Services Business',
      client_type: 'MSB',
      primary_jurisdiction: 'Canada',
    },
    methodologyName: 'Standard AML EWRA',
    engagementType: 'Risk Assessment',
    intakeSections: [
      { section: 'business_profile', responses: { legal_entity_name: 'TransCanada Money Transfer Ltd.', industry: 'Money Services Business - Remittances', country_of_incorporation: 'Canada', regulated: true, licenses_held: 'FINTRAC MSB Registration' } },
      { section: 'products_services', responses: { products_offered: 'International remittances and cross-border payment services', handles_fiat: true, handles_virtual_assets: false, accepts_cash: true, offers_remittances: true, offers_cross_border_services: true, monthly_transaction_volume: 5000000, avg_transaction_size: 500 } },
      { section: 'delivery_channels', responses: { services_in_person: true, services_offered_online: true, onboarding_fully_remote: false, transactions_through_web: true } },
      { section: 'customer_base', responses: { client_base: 'individuals', peps_permitted: true, foreign_customers_permitted: true } },
      { section: 'geography', responses: { cross_border_permitted: true, high_risk_jurisdictions: true, restricted_to_canada: false, countries_customers_located: 'Canada, Philippines, India, Mexico, Pakistan' } },
      { section: 'aml_controls', responses: { compliance_officer: true, aml_policies: true, procedures_documented: true, sanctions_screening: true, transaction_monitoring: true, staff_training: true, recordkeeping: true, identity_verification: true } },
      { section: 'service_providers', responses: { banking_partners: true, payment_providers: true, vendor_dd_completed: true } },
    ],
    scenarioRisks: [
      { risk_name: 'Remittance Services', likelihood: 2, impact: 2, controlEffectiveness: 'Partially Effective' },
      { risk_name: 'Cross-Border Payments', likelihood: 2, impact: 3, controlEffectiveness: 'Partially Effective' },
      { risk_name: 'Cash Handling Services', likelihood: 3, impact: 2, controlEffectiveness: 'Partially Effective' },
      { risk_name: 'Customers Located in High-Risk Jurisdictions', likelihood: 2, impact: 3, controlEffectiveness: 'Partially Effective' },
      { risk_name: 'Politically Exposed Persons', likelihood: 2, impact: 3, controlEffectiveness: 'Strong' },
      { risk_name: 'Sanctioned Jurisdiction Exposure', likelihood: 2, impact: 3, controlEffectiveness: 'Partially Effective' },
    ],
  },

  'Cheque Cashing Business': {
    defaultClientName: 'EasyCheck Services Inc.',
    clientData: {
      industry: 'Cheque Cashing',
      client_type: 'MSB',
      primary_jurisdiction: 'Canada',
    },
    methodologyName: 'Cash Business EWRA',
    engagementType: 'Risk Assessment',
    intakeSections: [
      { section: 'business_profile', responses: { legal_entity_name: 'EasyCheck Services Inc.', industry: 'Cheque Cashing and Cash Services', country_of_incorporation: 'Canada', regulated: true, licenses_held: 'FINTRAC MSB Registration' } },
      { section: 'products_services', responses: { products_offered: 'Cheque cashing, cash services', handles_fiat: true, handles_virtual_assets: false, accepts_cash: true, offers_cheque_cashing: true, offers_cross_border_services: false, avg_transaction_size: 800, monthly_transaction_volume: 500000 } },
      { section: 'delivery_channels', responses: { services_in_person: true, services_offered_online: false, onboarding_fully_remote: false, transactions_through_api: false } },
      { section: 'customer_base', responses: { client_base: 'individuals', peps_permitted: false, foreign_customers_permitted: false } },
      { section: 'aml_controls', responses: { compliance_officer: true, aml_policies: true, sanctions_screening: false, transaction_monitoring: false, staff_training: true, recordkeeping: false, identity_verification: true } },
      { section: 'cash_business_module', responses: { cash_accepted: true, cheque_cashing: true, realtime_review: true, structuring_mule_review: false, manual_exceptions: false, refusal_procedures: false } },
    ],
    scenarioRisks: [
      { risk_name: 'Cheque Cashing', likelihood: 3, impact: 2, controlEffectiveness: 'Partially Effective' },
      { risk_name: 'Cash Handling Services', likelihood: 3, impact: 2, controlEffectiveness: 'Partially Effective' },
      { risk_name: 'Retail Customers', likelihood: 1, impact: 1, controlEffectiveness: 'Strong' },
      { risk_name: 'High Transaction Velocity', likelihood: 2, impact: 2, controlEffectiveness: 'Weak' },
      { risk_name: 'Inadequate Recordkeeping', likelihood: 2, impact: 2, controlEffectiveness: 'Weak' },
      { risk_name: 'Weak Suspicious Transaction Reporting Procedures', likelihood: 2, impact: 3, controlEffectiveness: 'Weak' },
    ],
  },

  'Broken Compliance Program': {
    defaultClientName: 'CryptoEdge Exchange Ltd.',
    clientData: {
      industry: 'Virtual Asset Exchange',
      client_type: 'Virtual Asset Service Provider',
      primary_jurisdiction: 'Canada',
    },
    methodologyName: 'Virtual Asset EWRA',
    engagementType: 'Risk Assessment',
    intakeSections: [
      { section: 'business_profile', responses: { legal_entity_name: 'CryptoEdge Exchange Ltd.', industry: 'Virtual Asset Exchange', country_of_incorporation: 'Canada', regulated: true, licenses_held: 'FINTRAC MSB Registration' } },
      { section: 'products_services', responses: { products_offered: 'Bitcoin trading and fiat currency conversion', handles_fiat: true, handles_virtual_assets: true, accepts_cash: true, offers_cross_border_services: true, monthly_transaction_volume: 10000000, avg_transaction_size: 2500 } },
      { section: 'delivery_channels', responses: { services_offered_online: true, onboarding_fully_remote: true, transactions_through_api: true, services_in_person: false } },
      { section: 'customer_base', responses: { client_base: 'both', peps_permitted: true, foreign_customers_permitted: true } },
      { section: 'geography', responses: { cross_border_permitted: true, high_risk_jurisdictions: true } },
      { section: 'aml_controls', responses: { compliance_officer: false, aml_policies: false, procedures_documented: false, sanctions_screening: false, transaction_monitoring: false, staff_training: false, recordkeeping: false, independent_review: false, identity_verification: true } },
      { section: 'service_providers', responses: { third_party_kyc: false, banking_partners: true, vendor_dd_completed: false } },
      { section: 'technology_security', responses: { mfa: false, rbac: false, audit_logs: false, internally_developed_software: true } },
      { section: 'virtual_asset_module', responses: { supported_assets: 'BTC, ETH, various altcoins', external_wallets: true, onchain_screening: false, travel_rule: false } },
    ],
    scenarioRisks: [
      { risk_name: 'Virtual Asset Trading Services', likelihood: 3, impact: 3, controlEffectiveness: 'Weak' },
      { risk_name: 'Fiat On Off Ramp Services', likelihood: 3, impact: 2, controlEffectiveness: 'Weak' },
      { risk_name: 'Cash Handling Services', likelihood: 3, impact: 2, controlEffectiveness: 'Weak' },
      { risk_name: 'High Transaction Velocity', likelihood: 3, impact: 2, controlEffectiveness: 'Weak' },
      { risk_name: 'Non-Face-to-Face Onboarding', likelihood: 3, impact: 2, controlEffectiveness: 'Weak' },
      { risk_name: 'API Transaction Access', likelihood: 3, impact: 2, controlEffectiveness: 'Weak' },
      { risk_name: 'Politically Exposed Persons', likelihood: 3, impact: 3, controlEffectiveness: 'Weak' },
      { risk_name: 'Cross-Border Transaction Activity', likelihood: 3, impact: 3, controlEffectiveness: 'Weak' },
      { risk_name: 'Sanctioned Individual Exposure', likelihood: 3, impact: 3, controlEffectiveness: 'Weak' },
      { risk_name: 'Lack of Dedicated Compliance Officer', likelihood: 3, impact: 3, controlEffectiveness: 'Weak' },
      { risk_name: 'Inadequate AML Policies', likelihood: 3, impact: 3, controlEffectiveness: 'Weak' },
      { risk_name: 'Inadequate Recordkeeping', likelihood: 3, impact: 2, controlEffectiveness: 'Weak' },
      { risk_name: 'Insufficient Employee Training', likelihood: 3, impact: 2, controlEffectiveness: 'Weak' },
      { risk_name: 'Weak Suspicious Transaction Reporting Procedures', likelihood: 3, impact: 3, controlEffectiveness: 'Weak' },
      { risk_name: 'Cybersecurity Vulnerabilities', likelihood: 3, impact: 3, controlEffectiveness: 'Weak' },
      { risk_name: 'Unauthorized System Access', likelihood: 3, impact: 3, controlEffectiveness: 'Weak' },
    ],
  },
};