import React, { useState } from 'react';
import { base44 } from '@/api/base44Client';
import { useAuth } from '@/lib/AuthContext';
import { Link } from 'react-router-dom';
import { createPageUrl } from '@/utils';
import { ArrowLeft, FlaskConical, Sparkles, Trash2, CheckCircle2, ExternalLink, AlertTriangle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { SCENARIO_TYPES, SCENARIO_DEFINITIONS } from '../components/test/ScenarioData';
import { calculateInherentRisk, calculateResidualRisk, LIKELIHOOD_SCALE, IMPACT_SCALE, DEFAULT_TASKS } from '../components/scoring/riskScoringEngine';
import { logAudit } from '../components/util/auditLog';

export default function AdminTestScenarios() {
  const { user } = useAuth();
  const [scenarioType, setScenarioType] = useState('Canadian Bitcoin Exchange');
  const [clientName, setClientName] = useState('');
  const [autoRisks, setAutoRisks] = useState(true);
  const [autoTasks, setAutoTasks] = useState(true);
  const [autoControls, setAutoControls] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [result, setResult] = useState(null);

  const isAuthorized = user?.role === 'admin';
  if (!isAuthorized) {
    return (
      <div className="flex flex-col items-center justify-center h-64 gap-3">
        <AlertTriangle className="w-8 h-8 text-amber-500" />
        <p className="text-sm font-semibold text-slate-900">Access Restricted</p>
        <p className="text-xs text-slate-500">Super Admin or Compliance Admin role required.</p>
      </div>
    );
  }

  const scenario = SCENARIO_DEFINITIONS[scenarioType];
  const defaultName = `TEST - ${scenario.defaultClientName}`;
  const finalClientName = clientName.trim() || defaultName;

  async function generateScenario() {
    setGenerating(true);
    const scenarioDef = SCENARIO_DEFINITIONS[scenarioType];

    // Load reference data in parallel
    const [methodologies, riskLibrary, controlLibrary] = await Promise.all([
      base44.entities.Methodology.list(),
      autoRisks ? base44.entities.RiskLibrary.filter({ status: 'Active' }) : Promise.resolve([]),
      autoControls ? base44.entities.ControlLibrary.filter({ status: 'Active' }) : Promise.resolve([]),
    ]);

    const methodology = methodologies.find(m => m.name === scenarioDef.methodologyName);
    const riskLibraryMap = {};
    riskLibrary.forEach(r => { riskLibraryMap[r.risk_name] = r; });
    const controlLibraryMap = {};
    controlLibrary.forEach(c => { controlLibraryMap[c.control_name] = c; });

    // Create client
    const client = await base44.entities.Client.create({
      ...scenarioDef.clientData,
      legal_name: finalClientName,
      status: 'Active',
    });

    // Create engagement
    const engagement = await base44.entities.Engagement.create({
      client_id: client.id,
      client_name: finalClientName,
      engagement_type: scenarioDef.engagementType,
      methodology_id: methodology?.id || '',
      methodology_name: scenarioDef.methodologyName,
      status: 'Intake In Progress',
      notes: '[TEST DATA — Generated by Test Scenario Generator]',
    });

    // Create intake + tasks + risks in parallel
    const [intakeRecords, taskRecords, riskRecords] = await Promise.all([
      Promise.all(scenarioDef.intakeSections.map(s => base44.entities.IntakeResponse.create({
        engagement_id: engagement.id,
        section: s.section,
        responses: s.responses,
        notes: '[TEST DATA]',
      }))),
      autoTasks
        ? Promise.all((DEFAULT_TASKS[scenarioDef.engagementType] || []).map(task => base44.entities.Task.create({
            ...task,
            engagement_id: engagement.id,
            engagement_name: `${finalClientName} - ${scenarioDef.engagementType}`,
            client_name: finalClientName,
            status: 'Not Started',
            priority: 'Medium',
            notes: '[TEST DATA]',
          })))
        : Promise.resolve([]),
      autoRisks
        ? Promise.all(scenarioDef.scenarioRisks.map(riskDef => {
            const libRisk = riskLibraryMap[riskDef.risk_name];
            const inherentResult = calculateInherentRisk(riskDef.likelihood, riskDef.impact);
            const residual = calculateResidualRisk(inherentResult.rating, riskDef.controlEffectiveness);
            return base44.entities.EngagementRisk.create({
              engagement_id: engagement.id,
              risk_id: libRisk?.id || '',
              risk_name: riskDef.risk_name,
              risk_category: libRisk?.risk_category || '',
              is_suggested: true,
              is_accepted: true,
              status: 'Draft',
              inherent_likelihood_score: riskDef.likelihood,
              inherent_likelihood_rating: LIKELIHOOD_SCALE[riskDef.likelihood],
              inherent_impact_score: riskDef.impact,
              inherent_impact_rating: IMPACT_SCALE[riskDef.impact],
              inherent_risk_score: riskDef.likelihood * riskDef.impact,
              inherent_risk_rating: inherentResult.rating,
              overall_control_effectiveness: riskDef.controlEffectiveness,
              residual_risk_rating: residual,
              analyst_rationale: '[TEST DATA — Auto-generated scoring]',
            });
          }))
        : Promise.resolve([]),
    ]);

    // Create draft controls if enabled
    let controlRecords = [];
    if (autoControls && riskRecords.length > 0) {
      const controlsToCreate = [];
      for (let i = 0; i < scenarioDef.scenarioRisks.length; i++) {
        const riskDef = scenarioDef.scenarioRisks[i];
        const riskId = riskRecords[i].id;
        const libRisk = riskLibraryMap[riskDef.risk_name];
        const linkedNames = (libRisk?.linked_control_names || []).slice(0, 2);
        for (const controlName of linkedNames) {
          const libCtrl = controlLibraryMap[controlName];
          controlsToCreate.push({
            engagement_risk_id: riskId,
            engagement_id: engagement.id,
            control_id: libCtrl?.id || '',
            control_name: controlName,
            control_category: libCtrl?.control_category || '',
            control_present: riskDef.controlEffectiveness !== 'Weak',
            design_effectiveness: riskDef.controlEffectiveness,
            operational_effectiveness: riskDef.controlEffectiveness,
            consistency_of_application: riskDef.controlEffectiveness,
            control_rating: riskDef.controlEffectiveness,
            notes: '[TEST DATA]',
          });
        }
      }
      if (controlsToCreate.length > 0) {
        controlRecords = await Promise.all(controlsToCreate.map(c => base44.entities.ControlAssessment.create(c)));
      }
    }

    // Update engagement with overall risk rating
    if (riskRecords.length > 0) {
      const residuals = riskRecords.map(r => r.residual_risk_rating);
      const overallRating = residuals.includes('High') ? 'High' : residuals.includes('Moderate') ? 'Moderate' : 'Low';
      await base44.entities.Engagement.update(engagement.id, {
        overall_risk_rating: overallRating,
        status: 'Risk Analysis',
      });
    }

    setResult({
      clientId: client.id,
      clientName: finalClientName,
      engagementId: engagement.id,
      engagementType: scenarioDef.engagementType,
      intakeCount: intakeRecords.length,
      taskCount: taskRecords.length,
      riskCount: riskRecords.length,
      controlCount: controlRecords.length,
      allIds: {
        client: client.id,
        engagement: engagement.id,
        intake: intakeRecords.map(r => r.id),
        tasks: taskRecords.map(r => r.id),
        risks: riskRecords.map(r => r.id),
        controls: controlRecords.map(r => r.id),
      },
    });
    await logAudit({ userEmail: user?.email, objectType: 'TestScenario', objectId: engagement.id, action: 'test_data_generated', details: `Generated "${scenarioType}": ${finalClientName}` });
    setGenerating(false);
  }

  async function deleteScenario() {
    if (!result) return;
    setDeleting(true);
    const { allIds } = result;
    if (allIds.controls.length > 0) {
      await Promise.all(allIds.controls.map(id => base44.entities.ControlAssessment.delete(id)));
    }
    if (allIds.risks.length > 0) {
      await Promise.all(allIds.risks.map(id => base44.entities.EngagementRisk.delete(id)));
    }
    await Promise.all([
      ...allIds.intake.map(id => base44.entities.IntakeResponse.delete(id)),
      ...allIds.tasks.map(id => base44.entities.Task.delete(id)),
    ]);
    await base44.entities.Engagement.delete(allIds.engagement);
    await base44.entities.Client.delete(allIds.client);
    await logAudit({ userEmail: user?.email, objectType: 'TestScenario', objectId: allIds.engagement, action: 'test_data_deleted', details: `Deleted test scenario: ${result.clientName}` });
    setResult(null);
    setClientName('');
    setDeleting(false);
  }

  return (
    <div className="max-w-xl">
      <div className="flex items-center gap-3 mb-6">
        <Link to={createPageUrl('Admin')} className="p-2 rounded-lg hover:bg-slate-100 text-slate-500 transition-colors">
          <ArrowLeft className="w-4 h-4" />
        </Link>
        <div>
          <div className="flex items-center gap-2">
            <FlaskConical className="w-5 h-5 text-rose-500" />
            <h1 className="text-xl font-bold text-slate-900">Test Scenario Generator</h1>
          </div>
          <p className="text-xs text-rose-600 font-medium mt-0.5">Internal use only — Super Admin & Compliance Admin</p>
        </div>
      </div>

      {!result ? (
        <div className="bg-white rounded-xl border border-slate-200/60 p-6 space-y-5">
          <div>
            <Label>Scenario Type</Label>
            <Select value={scenarioType} onValueChange={v => { setScenarioType(v); setClientName(''); }}>
              <SelectTrigger className="mt-1.5"><SelectValue /></SelectTrigger>
              <SelectContent>
                {SCENARIO_TYPES.map(t => <SelectItem key={t} value={t}>{t}</SelectItem>)}
              </SelectContent>
            </Select>
          </div>

          <div>
            <Label>Client Name</Label>
            <Input
              className="mt-1.5"
              placeholder={defaultName}
              value={clientName}
              onChange={e => setClientName(e.target.value)}
            />
            <p className="text-xs text-slate-400 mt-1">Leave blank to use default: <span className="font-medium">{defaultName}</span></p>
          </div>

          <div className="space-y-3 border-t border-slate-100 pt-4">
            <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Options</p>
            <div className="flex items-center gap-3">
              <Checkbox id="autoRisks" checked={autoRisks} onCheckedChange={v => { setAutoRisks(v); if (!v) setAutoControls(false); }} />
              <Label htmlFor="autoRisks" className="cursor-pointer text-sm font-normal">Auto-generate suggested risks with draft scoring</Label>
            </div>
            <div className="flex items-center gap-3">
              <Checkbox id="autoTasks" checked={autoTasks} onCheckedChange={setAutoTasks} />
              <Label htmlFor="autoTasks" className="cursor-pointer text-sm font-normal">Auto-generate default engagement tasks</Label>
            </div>
            <div className="flex items-center gap-3">
              <Checkbox id="autoControls" checked={autoControls} disabled={!autoRisks} onCheckedChange={setAutoControls} />
              <Label htmlFor="autoControls" className={`cursor-pointer text-sm font-normal ${!autoRisks ? 'text-slate-400' : ''}`}>Auto-generate draft control selections</Label>
            </div>
          </div>

          <Button onClick={generateScenario} disabled={generating} className="w-full bg-slate-900 hover:bg-slate-800 gap-2 mt-2">
            <Sparkles className="w-4 h-4" />
            {generating ? 'Generating...' : 'Generate Scenario'}
          </Button>
        </div>
      ) : (
        <div className="space-y-4">
          <div className="bg-emerald-50 border border-emerald-200 rounded-xl p-5">
            <div className="flex items-center gap-2 mb-4">
              <CheckCircle2 className="w-5 h-5 text-emerald-600 flex-shrink-0" />
              <h3 className="text-sm font-semibold text-emerald-900">Scenario Generated Successfully</h3>
            </div>

            <div className="space-y-0 divide-y divide-emerald-100 mb-4">
              <div className="flex items-center justify-between py-2.5">
                <div>
                  <p className="text-[10px] text-emerald-600 uppercase font-semibold tracking-wider">Client</p>
                  <p className="text-sm font-medium text-slate-900 mt-0.5">{result.clientName}</p>
                </div>
                <Link to={createPageUrl(`ClientDetail?id=${result.clientId}`)} className="flex items-center gap-1 text-xs text-blue-600 hover:underline font-medium">
                  Open <ExternalLink className="w-3 h-3" />
                </Link>
              </div>
              <div className="flex items-center justify-between py-2.5">
                <div>
                  <p className="text-[10px] text-emerald-600 uppercase font-semibold tracking-wider">Engagement</p>
                  <p className="text-sm font-medium text-slate-900 mt-0.5">{result.engagementType}</p>
                </div>
                <Link to={createPageUrl(`EngagementDetail?id=${result.engagementId}`)} className="flex items-center gap-1 text-xs text-blue-600 hover:underline font-medium">
                  Open <ExternalLink className="w-3 h-3" />
                </Link>
              </div>
            </div>

            <div className="grid grid-cols-4 gap-2">
              {[
                ['Intake Sections', result.intakeCount],
                ['Tasks', result.taskCount],
                ['Risks', result.riskCount],
                ['Controls', result.controlCount],
              ].map(([label, count]) => (
                <div key={label} className="bg-white rounded-lg p-2.5 text-center border border-emerald-100">
                  <p className="text-xl font-bold text-slate-900">{count}</p>
                  <p className="text-[10px] text-slate-500 mt-0.5">{label}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-amber-50 border border-amber-200 rounded-lg px-4 py-2.5 text-xs text-amber-700">
            All generated records are tagged with <code className="font-mono bg-amber-100 px-1 rounded">[TEST DATA]</code>. Use the button below to delete all generated records cleanly.
          </div>

          <div className="flex gap-3">
            <Button variant="outline" onClick={() => { setResult(null); setClientName(''); }} className="flex-1">
              Generate Another
            </Button>
            <Button onClick={deleteScenario} disabled={deleting} className="flex-1 bg-red-600 hover:bg-red-700 text-white gap-2">
              <Trash2 className="w-4 h-4" />
              {deleting ? 'Deleting...' : 'Delete Generated Data'}
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}