import React from 'react';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import PageHeader from '@/components/ui/PageHeader';
import { AlertCircle, Check } from 'lucide-react';

export default function NW010BRoutingDiagnostic() {
  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <PageHeader
        title="Why NW-010B Classification Fix Report is Published to Reports Page"
        subtitle="Understanding output routing and visibility classification"
      />

      <Card className="p-6 border-l-4 border-amber-500 bg-amber-50">
        <h2 className="text-lg font-semibold text-amber-950 mb-2 flex items-center gap-2">
          <AlertCircle className="w-5 h-5" />
          The Problem Being Fixed
        </h2>
        <p className="text-amber-900 text-sm">
          Before NW-010B: Generated outputs (reports, docs, tools) were appearing on the wrong page due to loose visibility logic and missing canonical classification. For example, delivery gate outputs appeared as "Internal Tools" admin cards instead of on the Reports page.
        </p>
      </Card>

      <Card className="p-6">
        <h2 className="text-lg font-semibold text-slate-900 mb-4">Why This Report Belongs on Reports Page</h2>
        <div className="space-y-3">
          <div className="p-3 bg-slate-50 rounded border border-slate-200">
            <p className="font-semibold text-slate-900 text-sm">✓ It is a delivery gate output</p>
            <p className="text-slate-600 text-xs mt-1">Generated by DeliveryGateRunner as a structured verification report, not an admin action tool.</p>
          </div>
          <div className="p-3 bg-slate-50 rounded border border-slate-200">
            <p className="font-semibold text-slate-900 text-sm">✓ It is classified as report</p>
            <p className="text-slate-600 text-xs mt-1">outputClass = "report" in OutputRegistryItem. Report class items belong on Reports page.</p>
          </div>
          <div className="p-3 bg-slate-50 rounded border border-slate-200">
            <p className="font-semibold text-slate-900 text-sm">✓ It is published to GeneratedReport entity</p>
            <p className="text-slate-600 text-xs mt-1">Published with visibleOnReportsPage=true. The canonical report source is GeneratedReport.</p>
          </div>
          <div className="p-3 bg-slate-50 rounded border border-slate-200">
            <p className="font-semibold text-slate-900 text-sm">✓ It is NOT in AdminTools</p>
            <p className="text-slate-600 text-xs mt-1">visibleInAdminTools=false. This ensures it doesn't appear as an "Internal Tool" card.</p>
          </div>
        </div>
      </Card>

      <Card className="p-6">
        <h2 className="text-lg font-semibold text-slate-900 mb-4">The Routing Architecture</h2>
        <div className="space-y-4">
          <div className="grid grid-cols-3 gap-4">
            <div className="p-4 bg-blue-50 rounded border border-blue-200">
              <p className="font-semibold text-blue-900 text-sm">Reports Page</p>
              <p className="text-blue-700 text-xs mt-2">Sources from:</p>
              <p className="text-blue-600 text-xs font-mono mt-1">GeneratedReport</p>
              <p className="text-blue-600 text-xs font-mono">outputClass=report</p>
              <p className="text-blue-700 text-xs mt-2">Example:</p>
              <p className="text-blue-600 text-xs">Delivery gates, verification reports, audit reports</p>
            </div>
            <div className="p-4 bg-green-50 rounded border border-green-200">
              <p className="font-semibold text-green-900 text-sm">Documentation</p>
              <p className="text-green-700 text-xs mt-2">Sources from:</p>
              <p className="text-green-600 text-xs font-mono mt-1">HelpDoc, GeneratedReport</p>
              <p className="text-green-600 text-xs font-mono">outputClass=documentation</p>
              <p className="text-green-700 text-xs mt-2">Example:</p>
              <p className="text-green-600 text-xs">Governance guides, feature guides</p>
            </div>
            <div className="p-4 bg-purple-50 rounded border border-purple-200">
              <p className="font-semibold text-purple-900 text-sm">Admin Tools</p>
              <p className="text-purple-700 text-xs mt-2">Sources from:</p>
              <p className="text-purple-600 text-xs font-mono mt-1">OutputRegistryItem</p>
              <p className="text-purple-600 text-xs font-mono">outputClass=tool</p>
              <p className="text-purple-700 text-xs mt-2">Example:</p>
              <p className="text-purple-600 text-xs">Runnable utilities, maintenance tasks</p>
            </div>
          </div>
        </div>
      </Card>

      <Card className="p-6">
        <h2 className="text-lg font-semibold text-slate-900 mb-4">How NW-010B Enforces This</h2>
        <div className="space-y-2">
          <div className="flex items-start gap-3 p-3 bg-emerald-50 rounded">
            <Check className="w-5 h-5 text-emerald-600 flex-shrink-0 mt-0.5" />
            <div>
              <p className="font-semibold text-emerald-900 text-sm">OutputRegistryItem Entity</p>
              <p className="text-emerald-700 text-xs">Canonical source of truth for output classification. Every generated output has explicit class and visibility flags.</p>
            </div>
          </div>
          <div className="flex items-start gap-3 p-3 bg-emerald-50 rounded">
            <Check className="w-5 h-5 text-emerald-600 flex-shrink-0 mt-0.5" />
            <div>
              <p className="font-semibold text-emerald-900 text-sm">NormalizeOutputClassification</p>
              <p className="text-emerald-700 text-xs">Repairs historical misclassifications. Resets reports to report class, docs to documentation, etc.</p>
            </div>
          </div>
          <div className="flex items-start gap-3 p-3 bg-emerald-50 rounded">
            <Check className="w-5 h-5 text-emerald-600 flex-shrink-0 mt-0.5" />
            <div>
              <p className="font-semibold text-emerald-900 text-sm">Query Filters</p>
              <p className="text-emerald-700 text-xs">Reports page filters by outputClass=report. AdminTools filters by outputClass=tool. No leakage.</p>
            </div>
          </div>
          <div className="flex items-start gap-3 p-3 bg-emerald-50 rounded">
            <Check className="w-5 h-5 text-emerald-600 flex-shrink-0 mt-0.5" />
            <div>
              <p className="font-semibold text-emerald-900 text-sm">Visibility Flags</p>
              <p className="text-emerald-700 text-xs">Explicit visibility flags (visibleInReports, visibleInAdminTools, etc.) prevent inference errors.</p>
            </div>
          </div>
        </div>
      </Card>

      <Card className="p-6 bg-slate-50">
        <h2 className="text-lg font-semibold text-slate-900 mb-3">Implementation Detail</h2>
        <p className="text-slate-600 text-sm mb-4">
          This report was generated by the <code className="bg-white px-2 py-1 rounded text-xs font-mono">deliveryGateNW010B</code> function and published via <code className="bg-white px-2 py-1 rounded text-xs font-mono">publishNW010BReport</code> into:
        </p>
        <ul className="text-sm text-slate-600 space-y-1 ml-4">
          <li>• <strong>GeneratedReport</strong> entity (visibleOnReportsPage=true)</li>
          <li>• <strong>OutputRegistryItem</strong> (outputClass="report", visibleInReports=true)</li>
        </ul>
        <p className="text-slate-600 text-sm mt-4">
          This ensures the report appears on the Reports page and nowhere else, demonstrating that the classification fix works correctly.
        </p>
      </Card>
    </div>
  );
}