/**
 * NW-UPGRADE-076F-PHASE1: User migration verification.
 * Fetches Base44 User list and Nightwatch NwAuthUser list, compares emails.
 * Writes result to docs/NW-UPGRADE-076F-MIGRATIONCHECK_RESULT.md
 *
 * Usage (admin token required for nwAuthListUsers):
 *   BASE44_APP_ID=... BASE44_APP_BASE_URL=... BASE44_ACCESS_TOKEN=... npx tsx scripts/checkUserMigration.ts
 */

import { createClient } from '@base44/sdk';
import { writeFileSync } from 'fs';
import { join } from 'path';

const appId = process.env.BASE44_APP_ID || process.env.VITE_BASE44_APP_ID;
const appBaseUrl = process.env.BASE44_APP_BASE_URL || process.env.VITE_BASE44_APP_BASE_URL;
const token = process.env.BASE44_ACCESS_TOKEN || process.env.token;
const functionsVersion = process.env.BASE44_FUNCTIONS_VERSION || process.env.VITE_BASE44_FUNCTIONS_VERSION || 'prod';

async function run(): Promise<{ migration_required: boolean; missing_users: string[] }> {
  if (!appId || !appBaseUrl || !token) {
    throw new Error('Set BASE44_APP_ID, BASE44_APP_BASE_URL, and BASE44_ACCESS_TOKEN (admin token for nwAuthListUsers)');
  }

  const client = createClient({
    appId,
    token,
    appBaseUrl,
    functionsVersion,
    serverUrl: '',
    requiresAuth: false,
  });

  const base44Users = await (client.entities as Record<string, { list?: (opts?: unknown) => Promise<Record<string, unknown>[]> }>).User?.list?.() ?? [];
  const nwResult = await (client.functions as Record<string, (name: string, body?: unknown) => Promise<{ users?: Record<string, unknown>[] }>>).invoke?.('nwAuthListUsers', {}) ?? { users: [] };
  const nwUsers = nwResult.users ?? [];

  const base44Emails = new Set(
    (base44Users as Record<string, unknown>[])
      .map((u) => (u.email as string)?.trim?.()?.toLowerCase?.())
      .filter(Boolean)
  );
  const nwEmails = new Set(
    (nwUsers as Record<string, unknown>[])
      .map((u) => (u.email as string)?.trim?.()?.toLowerCase?.())
      .filter(Boolean)
  );

  const missing_users = [...base44Emails].filter((e) => !nwEmails.has(e));
  const migration_required = missing_users.length > 0;

  return { migration_required, missing_users };
}

run()
  .then((result) => {
    const docPath = join(process.cwd(), 'docs', 'NW-UPGRADE-076F-MIGRATIONCHECK_RESULT.md');
    const content = `# NW-UPGRADE-076F — Migration check result

Generated by \`scripts/checkUserMigration.ts\`.

- **migration_required:** ${result.migration_required}
- **missing_users:** ${JSON.stringify(result.missing_users)}

If \`migration_required\` is \`true\`, do not proceed with Base44 removal until these users are migrated to NwAuthUser or explicitly excluded.
`;
    writeFileSync(docPath, content, 'utf8');
    console.log('Result:', result);
    console.log('Written to', docPath);
    if (result.migration_required) {
      console.error('STOP: migration_required is true. Migrate missing users before Base44 removal.');
      process.exit(1);
    }
  })
  .catch((err) => {
    console.error('Migration check failed:', err);
    process.exit(1);
  });
